library(readr)
demonetization_tweets <- read_csv("C:/Users/DELL/Desktop/Demonetisation Project, DataByte/demonetization-tweets.csv")
View(demonetization_tweets)
text=demonetization_tweets$text
install.packages("tm")
library("NLP", lib.loc="~/R/win-library/3.3")
install.packages("wordcloud")
library("tm", lib.loc="~/R/win-library/3.3")
mycorpus <- Corpus(VectorSource(text))
mycorpus
mycorpus <- tm_map(mycorpus, content_transformer(tolower),lazy=TRUE)
removeURL <- function(x) gsub("http[^[:space:]]*", "", x)
mycorpus <- tm_map(mycorpus, removeURL,lazy=TRUE)
mycorpus <- tm_map(mycorpus, removePunctuation,lazy=TRUE)
mycorpus <- tm_map(mycorpus, removeNumbers,lazy=TRUE)
mycorpus <- tm_map(mycorpus, removeWords, c('rt','demonetisation','demonetization',stopwords('english')),lazy=TRUE)
mycorpus <- tm_map(mycorpus, stripWhitespace,lazy=TRUE)
mycorpusCopy <- mycorpus
mycorpus <- tm_map(mycorpus, stemDocument,lazy=TRUE)
mycorpus <- tm_map(mycorpus, stemCompletion, dictionary=mycorpusCopy,lazy=TRUE)
mycorpus<-tm_map(mycorpus, PlainTextDocument,lazy=TRUE)
myDtm <- DocumentTermMatrix(mycorpus)
